"use client";
import{useEffect,useMemo,useRef,useState}from"react";import{classify}from"../../lib/classify";
export default function Schedule(){const[items,setItems]=useState([]),[err,setErr]=useState("");const[tab,setTab]=useState("Pending");const[input,setInput]=useState("");const[draft,setDraft]=useState(null);const[saving,setSaving]=useState(false);const[listening,setListening]=useState(false);const rec=useRef(null);

function prepare(){if(!input.trim())return;const x=classify(input.trim());setDraft({...x,category:"Tasks",taskAction:input.trim()})}
function voice(){if(listening){rec.current?.stop();return}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setErr("Voice recognition support নেই");return}const r=new SR();rec.current=r;r.lang="bn-IN";r.interimResults=true;r.continuous=true;let final=input.trim();r.onstart=()=>setListening(true);r.onresult=e=>{let interim="";for(let i=e.resultIndex;i<e.results.length;i++){const x=e.results[i][0].transcript.trim();if(e.results[i].isFinal)final=(final+" "+x).trim();else interim=x}setInput((final+" "+interim).trim())};r.onend=()=>setListening(false);r.start()}
async function addTask(){if(!draft||saving)return;setSaving(true);try{const capturedAt=new Date().toISOString();const item={...draft,category:"Tasks",timestamp:capturedAt,capturedAt,entryDate:capturedAt.slice(0,10),status:"Todo",localId:crypto.randomUUID()};const r=await fetch("/api/entries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(item)});const d=await r.json();if(!r.ok||!d.ok)throw new Error();setItems(v=>[item,...v]);setInput("");setDraft(null);setErr("")}catch{setErr("Task save হয়নি—আবার চেষ্টা করুন।")}finally{setSaving(false)}}
useEffect(()=>{fetch("/api/diary").then(r=>r.json()).then(d=>d.ok?setItems((d.entries||[]).filter(x=>x.category==="Tasks")):setErr(d.error||"Schedule load হয়নি")).catch(()=>setErr("Schedule load হয়নি"))},[]);
const today=new Date();today.setHours(0,0,0,0);
function state(x){const s=(x.status||"").toLowerCase();if(/done|complete|completed/.test(s))return"Completed";if(!x.dueDate)return"No date";const d=new Date(x.dueDate+"T00:00:00");if(d<today)return"Overdue";if(d.getTime()===today.getTime())return"Today";return"Upcoming"}
const shown=useMemo(()=>items.filter(x=>tab==="Pending"?state(x)!=="Completed":state(x)===tab),[items,tab]);
return <main className="diaryShell"><div className="diaryTop"><a className="back" href="/">‹</a><div><h1>📅 My Schedule</h1><p>Pending work • due dates • reminders</p></div></div><section className="card scheduleAssistant"><div className="sectionTitle"><div><small>SCHEDULE ASSISTANT</small><h2>কী করতে হবে বলুন</h2></div></div><div className="scheduleComposer"><textarea value={input} onChange={e=>{setInput(e.target.value);setDraft(null)}} placeholder="যেমন: আগামীকাল সন্ধ্যা ৬টায় ADEN report fill করতে হবে"/><button onClick={voice}>{listening?"⏹ Stop":"🎤 Speak"}</button></div><button className="primary" onClick={prepare} disabled={!input.trim()}>Organize Task</button>{draft&&<div className="taskDraft"><b>{draft.taskAction}</b><div className="taskDue"><label>Due Date<input type="date" value={draft.dueDate||""} onChange={e=>setDraft({...draft,dueDate:e.target.value})}/></label><label>Time<input type="time" value={draft.dueTime||""} onChange={e=>setDraft({...draft,dueTime:e.target.value})}/></label></div><button className="primary save" onClick={addTask} disabled={saving}>{saving?"Saving…":"✓ Save to My Schedule"}</button></div>}</section><div className="filters">{["Pending","Overdue","Today","Upcoming","No date","Completed"].map(x=><button key={x} className={tab===x?"on":""} onClick={()=>setTab(x)}>{x}</button>)}</div>{err&&<div className="notice">{err}</div>}{shown.map((x,i)=><article className="entry" key={x.timestamp||i}><div className="entryHead"><span className="cat">{state(x)}</span><time>{x.dueDate||x.date||""}{x.dueTime?" • "+x.dueTime:""}</time></div><div className="entryText">{x.taskAction||x.original}</div>{x.project&&<div className="meta">Project: {x.project}</div>}</article>)}{!err&&!shown.length&&<div className="empty">এই section-এ কোনো কাজ নেই।</div>}<p className="foot">Tasks stay here until completed • Calendar reminder integration is next</p></main>}