"use client";
import{useEffect,useRef,useState}from"react";import{classify}from"../lib/classify";
const KEY="second-brain-queue";
export default function Home(){
 const[text,setText]=useState("");const[preview,setPreview]=useState(null);const[msg,setMsg]=useState("");const[queue,setQueue]=useState([]);const[busy,setBusy]=useState(false);const[listening,setListening]=useState(false);const[lang,setLang]=useState("bn-IN");const rec=useRef(null);
 useEffect(()=>{try{setQueue(JSON.parse(localStorage.getItem(KEY)||"[]"))}catch{setQueue([])}},[]);
 function persist(q){setQueue(q);localStorage.setItem(KEY,JSON.stringify(q))}
 function addPending(item){persist([{...item,localId:item.localId||crypto.randomUUID(),syncStatus:"Pending"},...queue])}
 function resolveEntryDate(raw){
 const now=new Date(),d=new Date(now),s=raw.toLowerCase();
 // Entry Date is when the activity happened. Future task deadlines must never change it.
 if(/গতকাল|yesterday|कल/.test(s))d.setDate(d.getDate()-1);
 else if(/day before yesterday/.test(s))d.setDate(d.getDate()-2);
 else{
  // Only explicit past-date wording may back-date the activity.
  const m=raw.match(/(?:on|dated|তারিখ|date)\s*(\d{1,2})(?:st|nd|rd|th)?/i);
  if(m){const day=+m[1];if(day>=1&&day<=31){d.setDate(day);if(d>now)d.setMonth(d.getMonth()-1)}}
 }
 return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-");
 }
 function organize(){if(!text.trim()){setMsg("আগে কিছু বলুন, লিখুন বা upload করুন।");return}setPreview({...classify(text.trim()),entryDate:resolveEntryDate(text.trim())});setMsg("")}
 async function send(item){const r=await fetch("/api/entries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(item)});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||"Save failed");return d}
 async function save(){if(!preview||busy)return;setBusy(true);const capturedAt=new Date().toISOString();const item={...preview,timestamp:capturedAt,capturedAt,entryDate:preview.entryDate||capturedAt.slice(0,10),localId:crypto.randomUUID()};try{await send(item);setMsg("✓ Google Drive-এ save হয়েছে।")}catch{addPending(item);setMsg("Google Drive-এ নিশ্চিত করা যায়নি—entry ফোনে Pending হিসেবে রাখা হয়েছে।")}finally{setBusy(false);setText("");setPreview(null)}}
 async function sync(){if(!queue.length||busy)return;setBusy(true);setMsg("Pending entry sync হচ্ছে…");const left=[];let done=0;for(const item of queue){try{await send(item);done++}catch{left.push(item)}}persist(left);setBusy(false);setMsg(done+(done===1?"টি":"টি")+" sync হয়েছে। "+(left.length?left.length+"টি এখনও Pending।":"সব Pending entry শেষ।"))}
 function speak(){if(listening){rec.current?.stop();return}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setMsg("Voice input-এর জন্য Android Chrome ব্যবহার করুন।");return}const r=new SR();rec.current=r;r.lang=lang;r.interimResults=true;r.continuous=false;let final="";r.onstart=()=>{setListening(true);setMsg("")};r.onresult=e=>{let interim="";for(let i=e.resultIndex;i<e.results.length;i++){const x=e.results[i][0].transcript;if(e.results[i].isFinal)final+=(final?" ":"")+x;else interim=x}setText((final||interim).trim());setPreview(null)};r.onerror=e=>{setListening(false);setMsg(e.error==="not-allowed"?"Microphone permission Allow করুন।":"কথা পরিষ্কার ধরা যায়নি। আবার চেষ্টা করুন।")};r.onend=()=>{setListening(false);if(final.trim())setMsg("Transcript দেখে ঠিক থাকলে Organize চাপুন।")};r.start()}
 async function upload(e){const f=e.target.files?.[0];if(!f)return;if(!/\.(txt|csv|json)$/i.test(f.name)){setMsg("এই মুহূর্তে TXT/CSV/JSON পড়তে পারছি। PDF/Word/Excel/Image support পরের upgrade-এ আসছে।");return}const v=(await f.text()).slice(0,10000);setText(v);setPreview(null);setMsg(f.name+" loaded — লেখাটি দেখে Organize চাপুন।")}
 return <main className="shell"><header><div className="brand">🧠</div><div><h1>The Second Brain</h1><p>বলুন, লিখুন বা upload করুন</p></div><span className={"badge "+(queue.length?"warn":"")}>{queue.length?queue.length+" Pending":"Drive ready"}</span></header>
 <a className="diaryButton" href="/finance"><span>💰</span><div><b>My Finance</b><small>income • expense • balance • savings</small></div><strong>›</strong></a><a className="diaryButton" href="/schedule"><span>📅</span><div><b>My Schedule</b><small>pending • today • upcoming • completed • tasks</small></div><strong>›</strong></a><a className="diaryButton" href="/diary"><span>📖</span><div><b>My Diary</b><small>সব saved entry • organized & searchable</small></div><strong>›</strong></a><section className="hero card"><div className="mode"><button className={listening?"active":""} onClick={speak}><span>{listening?"⏹":"🎤"}</span>{listening?"Stop":"Speak"}</button><button onClick={()=>document.getElementById("braintext")?.focus()}><span>✍️</span>Write</button><label><span>📎</span>Upload<input type="file" onChange={upload}/></label></div>
 <div className="lang"><span>Voice</span><select value={lang} onChange={e=>setLang(e.target.value)}><option value="bn-IN">বাংলা</option><option value="en-IN">English</option><option value="hi-IN">हिंदी</option></select></div>
 {listening&&<div className="listening"><i/>Listening… এখন বলুন</div>}
 <textarea id="braintext" value={text} onChange={e=>{setText(e.target.value);setPreview(null)}} placeholder="আপনার কথা এখানে দেখা যাবে। ভুল থাকলে save করার আগে ঠিক করে নিন…"/>
 <button className="primary" onClick={organize} disabled={!text.trim()}>✨ Organize & Preview</button>{msg&&<div className="notice">{msg}</div>}</section>
 {preview&&<section className="card review"><div className="sectionTitle"><div><small>STEP 2</small><h2>Save করার আগে দেখুন</h2></div><button className="edit" onClick={()=>{setPreview(null);document.getElementById("braintext")?.focus()}}>Edit</button></div><div className="raw">{preview.original}</div><label className="entryDate">📅 Entry Date<input type="date" value={preview.entryDate||""} onChange={e=>setPreview({...preview,entryDate:e.target.value})}/></label>{preview.category==="Tasks"&&<div className="taskDue"><label>Due Date<input type="date" value={preview.dueDate||""} onChange={e=>setPreview({...preview,dueDate:e.target.value})}/></label><label>Time<input type="time" value={preview.dueTime||""} onChange={e=>setPreview({...preview,dueTime:e.target.value})}/></label></div>}<div className="chips"><span>{preview.category}</span><span>{preview.language}</span>{preview.amount&&<span>₹{preview.amount}</span>}{preview.category==="Finance"&&preview.type&&<span>{preview.type}</span>}{preview.category==="Finance"&&preview.subcategory&&<span>{preview.subcategory}</span>}{preview.category==="Finance"&&preview.account&&<span>{preview.account}</span>}{preview.kmFrom&&<span>KM {preview.kmFrom} → {preview.kmTo}</span>}<span>{preview.status}</span></div><button className="primary save" disabled={busy} onClick={save}>{busy?"Saving…":"✓ Confirm & Save to Google Drive"}</button></section>}
 <section className="card sync"><div><small>SAFETY BACKUP</small><h2>Pending Sync</h2><p>{queue.length?queue.length+"টি entry এই ফোনে নিরাপদে আছে।":"কোনো pending entry নেই।"}</p></div>{queue.length>0&&<button onClick={sync} disabled={busy}>↻ {busy?"Syncing…":"Sync now"}</button>}</section>
 <p className="foot">Original text সবসময় রাখা হবে • Confirm না করলে Drive-এ save হবে না</p></main>
}